package by.etc.samodumkina.service;

public enum CommandName {
	REGISTRATION, SIGN_IN, NO_SUCH_COMMAND, TAKE_ALL_BOOKS, EN, RU, ADD_AS_LIKED_BOOK, SIGN_OUT,
	GET_LIKED_BOOKS_PAGE, GET_USER_LIKED_BOOKS, GET_CATALOG_PAGE, TAKE_BOOK_TO_HOME, TAKE_BOOK_TO_READING_ROOM,
	GET_ORDERS_STORY_PAGE, GET_ORDERS_PAGE, NEED_SEND_OUT_BOOKS_TO_HOME, NEED_SEND_OUT_BOOKS_TO_READING_ROOM,
	CREATE_ORDER, GET_ADMIN_ORDER_STORY_PAGE, GET_ADMIN_MAIN_PAGE, TAKE_ADMIN_ORDER_STORY, TAKE_USER_ORDERS, 
	TAKE_USER_ORDER_STORY, GET_ADD_NEW_BOOK_PAGE, GET_DELETE_BOOK_PAGE, ADD_NEW_BOOK
}
